import { ComponentType } from 'react'
import { ViewStyle } from 'react-native'
import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Apple,
  ArrowDownLeft,
  ArrowLeft,
  ArrowRight,
  ArrowRightFromLine,
  ArrowUpRight,
  AtSign,
  Award,
  Banknote,
  BarChart,
  BarChart3,
  Battery,
  Bell,
  Book,
  BrainCircuit,
  Building2,
  Calendar,
  Camera,
  Check,
  CheckCheck,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudLightning,
  CloudOff,
  CloudRain,
  CloudSun,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Droplets,
  Edit3,
  Egg,
  Eye,
  EyeOff,
  File,
  FileSpreadsheet,
  FileText,
  Filter,
  Fingerprint,
  FingerprintPattern,
  Flag,
  Flame,
  Globe,
  GraduationCap,
  Heart,
  HelpCircle,
  House,
  Image,
  Info,
  Key,
  Landmark,
  Lightbulb,
  ListChecks,
  Lock,
  LogIn,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Navigation,
  Package,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  PieChart,
  PiggyBank,
  Pill,
  Pin,
  Play,
  Plus,
  Printer,
  Radio,
  Receipt,
  RefreshCw,
  Reply,
  Rss,
  Save,
  Scale,
  ScanFace,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Skull,
  Smartphone,
  Smile,
  Sparkles,
  Sprout,
  Square,
  Star,
  Sun,
  Target,
  Thermometer,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Video,
  Volume2,
  Wallet,
  Wheat,
  Wifi,
  Wind,
  Wrench,
  X,
  XCircle,
  Zap,
} from 'lucide-react-native'
import { GoonaNairaIcon } from '../components/icons/GoonaNairaIcon'

export interface IconProps {
  size?: number | string
  color?: string
  strokeWidth?: number
  style?: ViewStyle
}

export type IconComponent = ComponentType<IconProps>

export const Icons = {
  activity: Activity,
  alertCircle: AlertCircle,
  alertOctagon: AlertOctagon,
  alertTriangle: AlertTriangle,
  apple: Apple,
  arrowDownLeft: ArrowDownLeft,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowRightFromLine: ArrowRightFromLine,
  arrowUpRight: ArrowUpRight,
  atSign: AtSign,
  award: Award,
  banknote: Banknote,
  barChart: BarChart,
  barChart3: BarChart3,
  battery: Battery,
  bell: Bell,
  book: Book,
  brainCircuit: BrainCircuit,
  building2: Building2,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  checkCheck: CheckCheck,
  checkCircle: CheckCircle,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  circle: Circle,
  circleAlert: CircleAlert,
  circleCheck: CircleCheck,
  circleX: CircleX,
  clipboardCheck: ClipboardCheck,
  clipboardList: ClipboardList,
  clock: Clock,
  cloud: Cloud,
  cloudLightning: CloudLightning,
  cloudOff: CloudOff,
  cloudRain: CloudRain,
  cloudSun: CloudSun,
  copy: Copy,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  download: Download,
  droplets: Droplets,
  edit3: Edit3,
  egg: Egg,
  eye: Eye,
  eyeOff: EyeOff,
  file: File,
  fileSpreadsheet: FileSpreadsheet,
  fileText: FileText,
  filter: Filter,
  fingerprint: Fingerprint,
  fingerprintPattern: FingerprintPattern,
  flag: Flag,
  flame: Flame,
  globe: Globe,
  graduationCap: GraduationCap,
  heart: Heart,
  helpCircle: HelpCircle,
  house: House,
  image: Image,
  info: Info,
  key: Key,
  landmark: Landmark,
  lightbulb: Lightbulb,
  listChecks: ListChecks,
  lock: Lock,
  logIn: LogIn,
  mail: Mail,
  mapPin: MapPin,
  megaphone: Megaphone,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  messagesSquare: MessagesSquare,
  mic: Mic,
  minus: Minus,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  navigation: Navigation,
  package: Package,
  paperclip: Paperclip,
  pause: Pause,
  pencil: Pencil,
  phone: Phone,
  pieChart: PieChart,
  piggyBank: PiggyBank,
  pill: Pill,
  pin: Pin,
  play: Play,
  plus: Plus,
  printer: Printer,
  radio: Radio,
  receipt: Receipt,
  refreshCw: RefreshCw,
  reply: Reply,
  rss: Rss,
  save: Save,
  scale: Scale,
  scanFace: ScanFace,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share2: Share2,
  shield: Shield,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  shoppingCart: ShoppingCart,
  skull: Skull,
  smartphone: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  sprout: Sprout,
  square: Square,
  star: Star,
  sun: Sun,
  target: Target,
  thermometer: Thermometer,
  trash2: Trash2,
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  triangleAlert: TriangleAlert,
  truck: Truck,
  user: User,
  userCheck: UserCheck,
  userMinus: UserMinus,
  userPlus: UserPlus,
  userX: UserX,
  users: Users,
  video: Video,
  volume2: Volume2,
  wallet: Wallet,
  wheat: Wheat,
  wifi: Wifi,
  wind: Wind,
  wrench: Wrench,
  x: X,
  xCircle: XCircle,
  zap: Zap,
  naira: GoonaNairaIcon,
} as const
